add codestyle ci

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -7,6 +7,16 @@ jobs:
     name: Lint
     runs-on: ubuntu-20.04
     steps:
+      - uses: actions/checkout@v3
+      - name: checkout develop
+        run: |
+          if ! git show-ref --quiet refs/heads/master; then \
+              echo "local develop branch is missing, creating local develop branch that tracks remote develop branch"
+              git fetch origin develop
+              git branch develop --track origin/master
+          else
+            echo "local master branch exist, skipping"
+          fi
       - uses: actions/setup-python@v1
         with:
           python-version: 3.8
